apiVersion: batch/v1
kind: CronJob
metadata:
  name: traffic-offpeak
  namespace: traffic
spec:
  schedule: "0/15 10-22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: pvc
          containers:
            - name: taffic
              image: ghcr.io/fredoaf/traffic-alerts:0.6.0
              imagePullPolicy: IfNotPresent
              env:
                - name: DATA_DIR
                  value: /app/data/
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: API_KEY
                      name: apikey
              volumeMounts:
                - mountPath: /app/data
                  name: storage
            # command:
          restartPolicy: OnFailure
