apiVersion: v1
data:
  run.sh: |
    #!/bin/sh
    echo "Starting"
    apk add jq curl
    curl -s -d "Container starting up" ntfy.sh/itsafarrenswim
    data=$(curl -s https://legacy.coursepro.co.uk/portal/api/HomePortal/booking/search?filter=%7B%22region%22:3,%22courseGroupCategory%22:%5B1%5D,%22centre%22:9,%22courseType%22:1,%22levelGroup1%22:%5B4%5D,%22level4%22:%5B265%5D,%22dayOfWeek%22:%5B6%5D,%22offset%22:0,%22limit%22:20%7D | jq  '.resultSet.results')
    while true; do
      if [ "$data" != "[]" ]; then
        echo $data
        curl -s -d "$data" ntfy.sh/itsafarrenswim
      fi
      sleep 3600
    done
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: entrypoint
  namespace: swimcheck
